import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {MASTERY_EVENTS,MASTERY_GENERATOR_VERSION,MASTERY_PHYSICS_VERSION} from '../../../../src/game/mastery/events';
import {createRecordIdentity,emptyMasteryProfile,parseMasteryProfile,recordIdentityKey,saveMasteryProfile} from '../../../../src/game/mastery/storage';
import type {MasteryRecord} from '../../../../src/game/mastery/types';
assert.equal(MASTERY_GENERATOR_VERSION,'inkstorm-course-9');assert.equal(MASTERY_PHYSICS_VERSION,'inkstorm-drive-4');
const current=createRecordIdentity({event:MASTERY_EVENTS[0]!,courseSeed:0x494e4b53,directorSeed:42,vehicleClass:'podracer'});
const previous={...current,generatorVersion:'inkstorm-course-8'},key=recordIdentityKey(previous),profile=emptyMasteryProfile();
const old:MasteryRecord={identity:previous,time:95,lapTimes:[95],sectors:[20,30,45],medal:'silver',recordedAt:'2026-09-08T00:00:00.000Z',ghost:{version:1,identityKey:key,duration:95,sampleHz:10,frames:[[0,1,2,3,0,0,0,0],[95,4,5,6,0,0,0,0]]}};
profile.records[key]=old;profile.records[recordIdentityKey(current)]={...old,identity:current,time:94,lapTimes:[94],ghost:null};
profile.favorites=[{id:'inkstorm-trial',title:'Saved course8',seed:previous.courseSeed,generatorVersion:previous.generatorVersion,savedAt:old.recordedAt}];
profile.history=[{id:'historic-run',eventId:'inkstorm-trial',time:95,placement:1,medal:'silver',valid:true,recordedAt:old.recordedAt}];
const archived={...old,identity:{...previous,generatorVersion:'inkstorm-course-7'},ghost:null};profile.archivedRecords=[archived];
const migrated=parseMasteryProfile(JSON.stringify(profile));
assert.deepEqual(migrated.archivedRecords.find(r=>r.identity.generatorVersion==='inkstorm-course-8'),{...old,ghost:null});
assert.equal(migrated.archivedRecords.length,2);assert.equal(migrated.archivedFavorites.length,1);assert.equal(migrated.favorites.length,0);
assert(!migrated.records[key]);assert.equal(Object.keys(migrated.records).length,1);assert.equal(migrated.records[recordIdentityKey(current)]!.time,94);assert.deepEqual(migrated.history,profile.history);
let saved='';assert.equal(saveMasteryProfile(migrated,{getItem:()=>saved,setItem:(_key,value)=>{saved=value;}}),null);assert.deepEqual(parseMasteryProfile(saved),migrated);
const receipt={status:'pass',from:previous.generatorVersion,to:current.generatorVersion,physicsVersion:MASTERY_PHYSICS_VERSION,archivedTimesAndSectorsRetained:true,archivedGhostPosesNotActive:true,oldFavoritesArchived:true,previousArchivesPreserved:true,historyPreserved:true,currentRecordActive:true,saveReloadIdempotent:true,scope:'Existing global generator edition migration also archives other event seeds, retaining existing 72-record/32-favorite limits; no new storage format.'};
writeFileSync('assets/source/inkstorm/launch-reveal-round31/migration-receipt.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));
