import assert from 'node:assert/strict';
import {writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {createProceduralPodraceCourse} from '../../../../src/game/race/course';
import {createCourseGulfField} from '../../../../src/game/race/CourseGulfField';
import {createCourseGulfField as controlField} from './original/CourseGulfField';
import {sampleTerrainHeight} from '../../../../src/render/terrain/terrainMath';
const dir='assets/source/inkstorm/launch-surface-join-round31';
const course=createProceduralPodraceCourse({heightAt:sampleTerrainHeight},0x494e4b53),a=controlField(course)!,b=createCourseGulfField(course)!;
let mainProbes=0,branchProbes=0,mainOutside=0,branchMax=0,mainMax=0,changeMin=Infinity,changeMax=-Infinity;
const offsets=[[0,0],[.85,0],[-.85,0],[0,.85],[0,-.85],[1.15,0],[-1.15,0],[0,1.15],[0,-1.15]];
const probe=(x:number,z:number,branch:boolean,distance:number)=>{for(const[dx,dz] of offsets){const delta=Math.abs(a.sampleOffset(x+dx!,z+dz!)-b.sampleOffset(x+dx!,z+dz!));if(branch){branchProbes++;branchMax=Math.max(branchMax,delta);}else{mainProbes++;mainMax=Math.max(mainMax,delta);if(distance<a.launchProfile.crestDistance-15||distance>a.launchProfile.crestDistance+45)mainOutside=Math.max(mainOutside,delta);if(delta>0){changeMin=Math.min(changeMin,distance);changeMax=Math.max(changeMax,distance);}}}};
for(let i=0;i<4096;i++){const p=course.samplePlanAtProgress(i/4096);for(const side of [-1,-.5,0,.5,1])probe(p.x+p.rightX*p.width*side,p.z+p.rightZ*p.width*side,false,p.distance);}
for(const branch of course.branches)for(let i=1;i<branch.points.length;i++){const p=branch.points[i-1]!,q=branch.points[i]!,length=Math.hypot(q.x-p.x,q.z-p.z),steps=Math.ceil(length/4);for(let k=0;k<=steps;k++){const t=k/steps,x=p.x+(q.x-p.x)*t,z=p.z+(q.z-p.z)*t,rx=(q.z-p.z)/length,rz=-(q.x-p.x)/length;for(const side of [-1,-.5,0,.5,1])probe(x+rx*Math.max(p.width,q.width)*side,z+rz*Math.max(p.width,q.width)*side,true,0);}}
assert.equal(mainOutside,0);assert.equal(branchMax,0);assert.deepEqual(a.grids[1].values,b.grids[1].values);
const gradeFor=(field:typeof a)=>{let maxGrade=0,at=0;for(let d=a.launchProfile.startDistance-20;d<a.launchProfile.endDistance+20;d+=2){const p=course.sampleAtDistance(d-4),q=course.sampleAtDistance(d+4),grade=Math.abs(sampleTerrainHeight(q.x,q.z,field)-sampleTerrainHeight(p.x,p.z,field))/8;if(grade>maxGrade){maxGrade=grade;at=d;}}return {maxGrade,at,window:8,spacing:2};};
const results=JSON.parse(readFileSync(`${dir}/probe-result.json`,'utf8'));
for(const s of results.salt)assert(s.minimum>(s.ahead===650?.9:1.4));
const keyRays=results.views.filter((v:any)=>['05-launch','launch-crest'].includes(v.id)).map((v:any)=>({id:v.id,candidateCameraMove:v.cameraError,targets:v.targets.filter((r:any)=>[450,600,800].includes(r.f)).map((r:any)=>({forward:r.f,margin:r.bm}))}));
for(const v of keyRays)for(const t of v.targets)assert(t.margin>1);
const grids=b.grids.map((g,i)=>{const old=a.grids[i]!;let changed=0,min=Infinity,max=-Infinity,maxDelta=0;for(let k=0;k<g.values.length;k++){const delta=g.values[k]!-old.values[k]!;if(delta!==0){changed++;min=Math.min(min,delta);max=Math.max(max,delta);maxDelta=Math.max(maxDelta,Math.abs(delta));}}assert.deepEqual([g.minX,g.minZ,g.cellSize,g.size],[old.minX,old.minZ,old.cellSize,old.size]);return{name:g.name,changed,minDelta:changed?min:0,maxDelta:changed?max:0,maxAbsoluteDelta:maxDelta,bytes:g.values.byteLength,sha256:createHash('sha256').update(new Uint8Array(g.values.buffer)).digest('hex')};});
const lateral=results.profiles.filter((p:any)=>p.d>=1500).map((p:any)=>({distance:p.d,originalMaxLateralGrade:p.maxGradeA,candidateMaxLateralGrade:p.maxGradeB}));
const receipt={status:'PASS: bounded source geometry and sightline audit; actual pixels/driving/performance remain untested',basis:'round31 current field with30m lip/12m throat shoulder',candidate:'local leading-radius correction rejoining within30m;48m throat shoulder',corridor:{mainProbes,branchProbes,total:mainProbes+branchProbes,maxLegalMainChange:mainMax,observedMainChangeDistance:[changeMin,changeMax],allowedMainDistance:[a.launchProfile.crestDistance-15,a.launchProfile.crestDistance+45],maxOtherMainChange:mainOutside,maxBranchChange:branchMax},grade:{original:gradeFor(a),candidate:gradeFor(b)},salt:results.salt.map((s:any)=>({ahead:s.ahead,minimum:s.minimum,threshold:s.ahead===650?.9:1.4})),keyRays,lateral,grids,budget:{addedTextures:0,addedMeshes:0,addedDrawCalls:0,addedShaderFetches:0,addedPerFrameWork:0},limits:['Terrain sightlines use3m steps to points3m above floor; exclude mesh occlusion and clipmap tessellation.','Main/branch normal invariants are dense discrete probes, not a continuous swept-volume proof.','The30m localized leading-radius correction changes legal lane heights; it requires repeat driving/landing checks within the unaccepted course9.','Cross-section grade maxima include other existing landform slopes.','Existing blunt scanned-rock terminations remain outside this one field-only correction.']};
writeFileSync(`${dir}/acceptance-source.json`,JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));
