from pathlib import Path
import json,hashlib,datetime
r=Path(__file__).resolve().parent
spec=[
 dict(id='rocket-propulsion',author='Iwan Gabovitch (qubodup)',title='Rocket Boost Engine Loop.wav',published='2012-02-16',license='CC0-1.0',licenseUrl='https://creativecommons.org/publicdomain/zero/1.0/',page='https://freesound.org/people/qubodup/sounds/146770/',pageFile='research/rocket-boost.html',download='https://cdn.freesound.org/previews/146/146770_71257-hq.mp3',file='rocket-boost-hq.mp3',role='Main propulsion bed',provenance='Creator describes sound made for a robot flight game. Public HQ preview, not login-required original WAV. Existing sound design, not claimed real jet recording.'),
 dict(id='little-robot',author='Little Robot Sound Factory',title='Sci-Fi Sound Effects Library',published='2015-04-13',license='CC-BY-3.0',licenseUrl='https://creativecommons.org/licenses/by/3.0/',page='https://opengameart.org/content/sci-fi-sound-effects-library',pageFile='research/little-robot-sci-fi.html',download='https://opengameart.org/sites/default/files/Sci-Fi%20Sound%20Library.zip',file='Sci-Fi-Sound-Library.zip',role='Medium spacecraft rival loop; Laser09 weapon; Laser07 shield/EMP',provenance='Author published premixed spaceship, laser and warp library including original48kHz WAVs; use OGA package CC-BY3 license. These are existing conventional designed effects, not real spacecraft recordings. Large0.493s and Small engine loops are research-only.'),
 dict(id='jet-boost',author='dklon',title='Jet Engine Takeoff',published='2013-05-13',license='CC-BY-3.0',licenseUrl='https://creativecommons.org/licenses/by/3.0/',page='https://opengameart.org/content/jet-engine-takeoff',pageFile='research/jet.html',download='https://opengameart.org/sites/default/files/engine_takeoff.wav',file='engine_takeoff.wav',role='Boost launch transient',provenance='Author describes jet takeoff with Doppler applied; credit dklon. Existing effect, recording equipment/source not specified.'),
 dict(id='hull-impact',author='7of9Designs',title='Heavy Metal Thud on Ground',published='2022-06-29',license='CC0-1.0',licenseUrl='https://creativecommons.org/publicdomain/zero/1.0/',page='https://freesound.org/people/7of9Designs/sounds/640204/',pageFile='research/heavy-metal-thud.html',download='https://cdn.freesound.org/previews/640/640204_12131847-hq.mp3',file='heavy-metal-thud-hq.mp3',role='Hull/ground collision and weapon impact',provenance='Creator describes heavy metal object hitting dirt with dirt sound. Public HQ preview, not login-required uploaded original MP3.'),
 dict(id='rupture',author='Michel Baradari',title='2 High Quality Explosions',published='2009-08-14',license='CC-BY-3.0',licenseUrl='https://creativecommons.org/licenses/by/3.0/',page='https://opengameart.org/content/2-high-quality-explosions',pageFile='research/explosions.html',download='https://opengameart.org/sites/default/files/explosions.7z',file='explosions.7z',role='Wreck/mine blast',provenance='Package includes info.txt confirming author and CC-BY3. Existing catalogued blast, not claimed live explosion recording.'),
]
for s in spec:
 for field in ['file','pageFile']:s[field+'Sha256']=hashlib.sha256((r/s[field]).read_bytes()).hexdigest()
record=dict(retrievedAt=datetime.datetime.now(datetime.timezone.utc).isoformat(),status='PRIMARY_SOURCE_LICENSE_VERIFIED_RUNTIME_CANDIDATE_PENDING_OWNER_AUDITION',sources=spec,retained=[dict(sourceManifest='assets/source/audio-salt-dusk/SOURCE_MANIFEST.json',runtime='public/audio/salt-dusk/juggernaut.mp3',author='Scott Buckley',license='CC-BY-4.0',role='Unchanged75second licensed music excerpt'),dict(sourceManifest='assets/source/audio-salt-dusk/SOURCE_MANIFEST.json',runtime='public/audio/salt-dusk-v2/mechanical-click.ogg',author='Kenney',license='CC0-1.0',role='Only dry mechanical click retained; no old beeps/jingles')],researchOnly=['wood-and-metal.zip and extracted metal samples: no runtime admission; mostly high ringing impact energy, unsuitable as main hull thud','Other Little Robot engine/laser/warp/ambience WAVs: comparison only, no runtime import'],listening='No perceptual listening tool was available; signal measurements are not a listening-quality judgment. No audio generation used.')
(r/'SOURCE_MANIFEST.json').write_text(json.dumps(record,indent=2)+'\n')
